base_url = "https://123sonic321.github.io/AutoBSC-Fa"
title = "AutoBSC-Fa"
description = "میخوای همۀ جوایز سایت چمپیونشیپ رو بگیری اما زمان یا حوصلۀ تماشای استریم رو نداری یا استریم در منطقه زمانیت مناسب نیست؟ ++AutoBSC به کمک شما اومده!"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"
